spring.application.name=banking-system
spring.profiles.default=local

spring.jpa.open-in-view=false

spring.web.locale=pl_PL
spring.web.locale-resolver=fixed

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=${JWT_EXPIRATION:86400000}
